# Generated by Django 4.2.6 on 2023-10-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default='No text'),
        ),
    ]
