# Generated by Django 4.2.6 on 2023-11-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
